### ISSUE TITLE
Official Launch Landing Page

### ISSUE THREAD

**Issue by adrianmc** [hyperh/react-forge-landing#2]
@hyperh has created a draft mockup. It looks awesome! Let's discuss and refine further.

Here's the latest:

![mockup](http://i.imgur.com/CVLxzRV.jpg)

**Comment by hyperh** [comment]
If you guys are good with this, we can start actually coding it.

**Comment by hyperh** [comment]
Also, if we are good with this, I can design the Previous Work page too now.

**Comment by adrianmc** [comment]
@hyperh @chunsli 
Since we already have a workable landing page up, we can actually use this as a test deliverable?

**Comment by adrianmc** [comment]
I'm not married to the idea tho, I dunno what you guys think.

**Comment by chunsli** [comment]
the general principle should be to use color where we want users to be attracted to. So i feel that there are a little bit too much patterns and the call to action is not standing out enough. I would probably prefer the background of the top triangle shape to be plain? and the illustration to be grey scale unless hovered, and removing patterns for the background of the call to action button "submit your design". do users have to scroll down to reach submit your design?

**Comment by hyperh** [comment]
Previous work screen. Lol it looks so empty

<img width="412" alt="screen shot 2016-06-14 at 4 38 15 pm" src="https://cloud.githubusercontent.com/assets/11323591/16036441/8e106408-324e-11e6-8466-e745e4a11123.png">

**Comment by adrianmc** [comment]
@chunsli @hyperh Let's use real data to hammer this design out: http://goodui.org

**Comment by adrianmc** [comment]
I agree the CTA can maybe be another highlight colour so that it stands out more. I do like the patterned background at the top though, but maybe we can darker/filter it so it's less distracting.

**Comment by adrianmc** [comment]
@chunsli I disagree about making the illustration greyscale, although it's possible to de-saturate it a little bit if you think it's too sharp. I feel like we're starting to pick at too many details here tho. But if it strongly bothers you, we should try to resolve it.

**Comment by hyperh** [comment]
I also disagree about it being greyscale.

I agree the CTAs should stand out more though. I'll look through the goodui stuff.

**Comment by chunsli** [comment]
ok, let's go with it, i have no strong opinions with this. test it out and we will see, i think we can start coding it too.

**Comment by hyperh** [comment]
Will implement goodui 5, 18

**Comment by adrianmc** [comment]
@hyperh it seems that number 18 shows a *negative* effect though? http://www.goodui.org/evidence/test006

Although I think it's because there are too many words within a button.

**Comment by hyperh** [comment]
@adrianmc, didn't see that. Man they should make the things with potential negative effect more obvious

**Comment by hyperh** [comment]
I would have thought a page about good UI would only be giving me good advice lol

**Comment by adrianmc** [comment]
@hyperh at the bottom of the page, it reads:

> Not All Of The Above Ideas Work. Find Out Which Do!

Kind of a "gotcha", but understandably they are running a business based on data.

**Comment by adrianmc** [comment]
Also, it may not necessarily be a good idea to put a CTA near the top:
https://blog.kissmetrics.com/why-the-fold-is-a-myth/

**Comment by hyperh** [comment]
<img width="486" alt="screen shot 2016-06-14 at 7 45 32 pm" src="https://cloud.githubusercontent.com/assets/11323591/16041553/9370c928-3268-11e6-9ac4-56a13187d55f.png">

**Comment by hyperh** [comment]
Clarified offer of 1 single page.

<img width="464" alt="screen shot 2016-06-14 at 7 54 39 pm" src="https://cloud.githubusercontent.com/assets/11323591/16041766/dedf8c68-3269-11e6-9852-d74aa7175a9d.png">

**Comment by adrianmc** [comment]
@hyperh 

#### "Save your time writing code. Focus on design."

I think it should be less designer-oriented and more developer-oriented. I prefer the copy/targeting that we have on our [current page](http://ReactForge.com) (well... obviously, because I wrote it lol). So probably more along the lines of:

- "Stop wasting time writing React.js components from scratch"
- "Focus on the data/logic"
- "No more worrying about styling (or CSS)"
- Any combination of the above 
- Take a look at what I've written already on [ReactForge.com](http://ReactForge.com)

**Rationale**
I know that CSS and styling is a REAL pain point for a lot of devs. Josh Owens even said it himself. He prefers to only have to deal with data, and prefers someone else to take care of all the CSS styling for him. In an ideal world, most of these devs would only want to touch plain Javascript. Even React.js quirks are annoying.

That being said, great work; it really looks very put together.

#### Other Comments

I think we should do one of the two following things in order to make sure we don't spend too much time on this.

##### 1. Remove the About Page

I'm not sure that it's necessary. In fact, I originally only imagined one single page for the entire site. It was @chunsli who brought up the "Prior Work" page. And I agree that it is a good idea, but I am still unsure about whether or not it's necessary for MVP. The About page has even less value, relatively speaking.

##### 2. Combine the About and Previous Work Pages

An alternative is to simply combine the About and Previous Work pages into one single page titled **Who we are** or **The Team** or whatever sounds good. That way, it's just one single page where people can look into our background and feel more comfortable about giving us money. But if that's the case, maybe we should consider option 3.

##### 3. Bring everything into just One Page

This is my favourite, but I haven't thought too much about how to organize it yet. Thoughts guys?

**Comment by hyperh** [comment]
@adrianmc Ahhh I wasn't aware that the copy on the live site was actually what you wanted. I'll integrate them.

**Comment by adrianmc** [comment]
@hyperh That's a good idea. Yes, integrate those 3 benefits or just the spirit of what's written there is fine too, it doesn't necessarily have to be a row of 3 items. Everything else, I'll leave up to you. You have absolute creative freedom.

**Comment by chunsli** [comment]
I like it a lot more guys, great work!!
Single page sounds good enough honestly!
Probably can reiterate the submit your design button.
The orange on blue is brilliant!

**Comment by hyperh** [comment]
I just integrated those 3 things in there directly. Do we need The Team in there really? I'm good with going without it.

<img width="207" alt="screen shot 2016-06-14 at 10 06 10 pm" src="https://cloud.githubusercontent.com/assets/11323591/16045709/44e34434-327c-11e6-86fc-0eaea3797c81.png">

**Comment by adrianmc** [comment]
@hyperh 
I feel we need a CTA before "Out Previous Work". Either that, or we switch the ordering of the current CTA section with the Prev Work section. But that might make it look kinda weird.

What about putting in another CTA button right above or below the 3 items?

Also, the items need their title for easy skimming. See existing page for what I mean.

**Comment by hyperh** [comment]
I'm ok with logo, doesn't always have to be within a circular shape. Could be within a flattened hex or w/e.

Fixed missing titles on the 3 cols.
Moved CTA up and Previous Work down. It doesn't seem that odd actually.

<img width="347" alt="screen shot 2016-06-15 at 12 43 08 am" src="https://cloud.githubusercontent.com/assets/11323591/16051389/2a165e14-3292-11e6-90bd-808f1efa7b69.png">

**Comment by adrianmc** [comment]
@hyperh The logo really bothers me, can you tell me what font you used for the "REACT FORGE" text and maybe I'll try to come up with something? I know I'm being anal, but I still wanna try.

**Comment by hyperh** [comment]
Roboto

**Comment by hyperh** [comment]
Feel free to change font too

**Comment by adrianmc** [comment]
I've made a logo in 3 different configurations (Rectangle, Square 1, Square 2) and in 5 different fonts (Klinic Slab, Lato, Montserrat, Roboto, Helvetica):

![screen shot 2016-06-15 at 3 21 51 am](https://cloud.githubusercontent.com/assets/943555/16056595/c5f32734-32a8-11e6-997d-63a3b2913296.png)

Let me know what you think.

**Comment by hyperh** [comment]
I like Klinic Slab, but the cross looks busy to me. I think I might prefer the original with Klinic.

**Comment by hyperh** [comment]
We've agreed that this is the final one

<img width="309" alt="screen shot 2016-06-15 at 7 24 17 pm" src="https://cloud.githubusercontent.com/assets/11323591/16078004/d3627538-332e-11e6-9fe4-d866b865c4a8.png">
